apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sblocktaginsteadofsha
  annotations:
    description: Blocks images with the versioning tag instead of sha.
spec:
  crd:
    spec:
      names:
        kind: K8sBlockTagInsteadOfSha
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            excludedContainers:
              type: array
              items:
                type: string
  targets:
      - target: admission.k8s.gatekeeper.sh
        rego: |
          package k8sblocktaginsteadofsha
          violation[{"msg": msg, "details": {}}]{
            input.review.object.kind == "Pod"
            imagename := input.review.object.spec.containers[_].image
            container := input_containers[_]
            not input_container_excluded(container.name)
            not contains(imagename, "@sha256:")
            msg := sprintf("Image not using \"sha256\" tag is not allowed. Container <%v>, image <%v>", [container.name, container.image])
          }

          input_containers[c] {
              c := input.review.object.spec.containers[_]
          }
          input_containers[c] {
              c := input.review.object.spec.initContainers[_]
          }
          input_containers[c] {
            c := input.review.object.spec.ephemeralContainers[_]
          }
          input_container_excluded(field) {
              field == input.parameters.excludedContainers[_]
          }
