name: Policy Remediation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' #Every Day at 20:00

permissions:
  id-token: write
  contents: read

jobs:
  policy-remediation:
    environment: prod
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Step 2: Log in to Azure
      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      # Step 3: Terraform Drift Detection for all folders under /src
      - name: check policy to remediate
        shell: bash
        run: src/scripts/policy_remediation.sh
