name: Static Analysis

on:
  push:

jobs:
  static_analysis:
    runs-on: ubuntu-22.04

    steps:
      # from https://github.com/actions/checkout/commits/main
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: init_src
        env:
          FOLDERS: >
            01_custom_roles
            02_policy_application_gateway
            02_policy_audit_logs
            02_policy_cosmosdb
            02_policy_dns
            02_policy_event_hub
            02_policy_kubernetes
            02_policy_resource_lock
            02_policy_metrics_logs
            02_policy_tags_inherit_from_subscription
            03_policy_set
            04_policy_assignments
            governance
        run: |
          TAG=$(cat .terraform-version)
          cd src/
          for f in $FOLDERS; do
            cd $f
            rm -rf 99_terraform.tf
            mv 99_terraform.tf.ci 99_terraform.tf
            docker run -v $(pwd):/tmp -w /tmp hashicorp/terraform:$TAG init
            cd ..
          done

      - name: run_test
        run: |
          # from https://github.com/antonbabenko/pre-commit-terraform/pkgs/container/pre-commit-terraform
          TAG="v1.77.0@sha256:64ce1e4b99d85497fe646db0724669039b079b45fa8cd503b4dc23dbdca490ae"
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
