name: Terraform Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' #Every Monday at 9:00


permissions:
  id-token: write
  contents: read

env:
  DIR: "src/"

jobs:
  terraform-drift-detection:
    environment: prod
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # Step 2: Setup Terraform
      - name: Set Terraform Version
        id: env_tf_version
        run: |
          echo "terraform_version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        id: terraform_setup
        name: Setup Terraform
        with:
          terraform_version: ${{ steps.env_tf_version.outputs.terraform_version }}
          terraform_wrapper: true

      # Step 3: Log in to Azure
      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      # Step 4: Terraform Drift Detection for all folders under /src
      - name: Terraform Drift Detection for all folders under /src
        env:
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: 'true'
        run: |
          cd $DIR
          # Loop through each folder under /src dynamically
          for folder in $(ls -d */); do
            echo "Running Terraform plan for $folder"

            # Change into the directory
            cd $folder
            
            export exitcode=0
            ./terraform.sh plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
        
            echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
           if [ $exitcode -eq 2 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi
           done
